# Generated by Django 3.2.7 on 2021-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_notifications_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
