# Generated by Django 3.2.7 on 2021-09-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_serie_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pupil', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
