# Generated by Django 3.2.7 on 2021-10-03 16:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
