# Generated by Django 3.2.7 on 2021-10-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
        migrations.AddField(
            model_name='training',
            name='Trainer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='trainer.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='pupil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='trainer.pupil'),
            preserve_default=False,
        ),
    ]
