# Generated by Django 3.2.7 on 2021-10-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20211003_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='Trainer',
            new_name='trainer',
        ),
    ]
